all: example.pdf example_abstract_only.pdf example_article_only.pdf \
     abstract_examples.pdf abstract1.pdf abstract2.pdf

%.pdf: %.ps
	ps2pdf $^ $@

%.gz: %
	gzip $^

%.ps: %.dvi
	dvips -Ppdf -o $@ $^

%.dvi: %.tex
	latex $^
	latex $^

%.tar: %.tex $(wildcard %.eps)
	tar -zcf $@ $^

